# Generated by Django 4.1.7 on 2023-03-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=64)),
                ('logo', models.TextField()),
                ('descripcion', models.TextField()),
                ('slogan', models.TextField()),
                ('fb', models.TextField()),
                ('ubicacion', models.TextField()),
                ('cel', models.CharField(max_length=12)),
                ('formulario', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
