# Generated by Django 4.1.7 on 2023-03-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Informacion'},
        ),
    ]
